version: '3.4'

services:
  saincraft:
    image: saincraft
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
